#!/bin/bash
#
#----------------------------------------------
#- The console display manager configuration.--
#----------------------------------------------

binlist=(
	'startx'
	'/bin/bash'
)
namelist=(AwesomeWM Terminal)
flaglist=(C C)

# See /usr/share/doc/cdm/themes for themes.
dialogrc=/usr/share/doc/cdm/themes/cdm

# Index of the first item in the menu.
countfrom=1

# Set default display
display=5

# Where should the first X tty be spawned?
xtty=3

# Should cdm(1) stick to the specified display?
locktty=yes

# Additional arguments to pass to X server
serverargs=(-nolisten tcp)

# Disable ConsoleKit
consolekit=no

# Alternative method to start X not as expected
altstartx=yes

# Destination from stdout and stderr from startx
startxlog=/dev/null
